### ISSUE TITLE
release current version

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/aoi#17]

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@yegor256 can you please help, what am I doing wrong here?

**Comment by yegor256** [comment]
@OlesiaSub it was a fault on my side. try again

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@OlesiaSub `groupId` is wrong in `pom.xml`

**Comment by OlesiaSub** [comment]
@yegor256 thanks, didn't notice it myself! and thanks for the previous answer too

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@yegor256 apparently permission to my repo is denied for rultor. is it my configuration mistake?

**Comment by yegor256** [comment]
@OlesiaSub should be fine now, try to release again

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.2`

**Comment by OlesiaSub** [comment]
@yegor256 if you have time, please look at the last two attempts to make a release (above).
The last but one attempt failed, because I can't modify data, which is already stored somewhere. So I had to change release version to make it work, filenames were changed and treated as new ones.
But isn't it strange, that even though version 0.0.1 was not released, I couldn't use 0.0.1 as a release tag because files with this tag were already stored somewhere for some reason?

**Comment by yegor256** [comment]
@OlesiaSub the JAR was deployed to Maven Central and _then_ rultor failed to create a release in GitHub, because of not enough permissions. When you tried to release again, Maven Central refused you.

**Comment by OlesiaSub** [comment]
@yegor256 hmm ok, got it. 
thanks for your help!
