### ISSUE TITLE
Bug when generating ${PATH}_aoi directory

### ISSUE THREAD

**Issue by c71n93** [objectionary/aoi#43]
According to the `README`, when passing a path to directory with `xmir` files (`/path/to/examples/`), the tool will generate a new directory with modified xmirs (`/path/to/examples_aoi/`). 

But now when passing a path `/path/to/examples/`, tool generates:
<img width="306" alt="Screenshot 2023-03-05 at 13 47 02" src="https://user-images.githubusercontent.com/70313618/222955822-1e027a74-1c9c-479c-b78d-6cbce88baacd.png">
Where files, that starts with `_aoi` are the modified files. That's not how it's supposed to work.

@advasileva have you ever faced this problem?

**Comment by c71n93** [comment]
@advasileva Okay, I found out, that this happens only when the directory is specified as `/path/to/examples/`. When I accidentally specified a directory as `/path/to/examples` (without closing `/`) it worked fine: new directory `/path/to/examples_aoi/` with modified xmirs was generated.

**Comment by c71n93** [comment]
But anyway it seems to me that this is a bug and it should be fixed

**Comment by advasileva** [comment]
@c71n93 I have never met this problem. It's good that the problem was found, this behavior looks illogical, it would be cool to fix it.
